#!/usr/bin/env python3
from hoja_con_formulas import generar_excel_personalizado

config = {
    "sheets": [
        {
            "title": "D111",
            "regions": [
{        "data": [["Grupo ", "D111", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "F", "Aula 8", "ICD", "Aula 7", "AL", "Aula 7*", "AM I", "Aula 7*", "AL", "Aula 7*", "", "AL", "Álgebra Lineal", "3", "0", "", "", "Aula 8,Aula 7,Aula 7*,Aula 7*,Aula 7*", ""], ["", "Turno 2", "L", "Aula 6*", "AL", "Aula 6*", "EF", "SEDER", "L", "Aula 7", "", "", "", "L", "Lógica", "2", "0", "", "", "Aula 6*,Aula 6*,SEDER,Aula 7", ""], ["", "Turno 3", "IP", "Aula 7", "AM I", "Aula 6*", "AM I", "Aula 7*", "IP", "Lab", "", "", "", "IP", "Introducción a la Programación", "2", "0", "", "", "Aula 7,Aula 6*,Aula 7*,Lab", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "AM I", "Análisis Matemático I", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "ICD", "Introducción a la Ciencia de Datos", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "F", "Filosofía", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "D211",
            "regions": [
{        "data": [["Grupo ", "D211", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "MA", "Matemática y Aplicaciones", "2", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "Prb", "Probabilidades", "2", "0", "", "", "", ""], ["", "Turno 3", "", "", "", "", "", "", "", "", "", "", "", "BD", "Bases de Datos", "2", "0", "", "", "", ""], ["", "Turno 4", "ED", "c 7", "BD", "c 7", "MA (EDO) cp 6 (con", "C211", "BD", "cp 7", "", "", "", "ED", "Estructura de Datos", "2", "0", "", "", "c 7,c 7,C211,cp 7", ""], ["", "Turno 5", "VD", "c 7", "EP", "c 7", "EP", "c 7", "Prb", "cp 7", "", "", "", "VD", "Visualización de Datos", "2", "0", "", "", "c 7,c 7,c 7,cp 7", ""], ["", "Turno 6", "MA", "c 6", "Prb", "c 7", "EF 4:45pm a 5:35pm", "", "ED", "cp 7", "", "", "", "EP", "Economía Política", "2", "0", "", "", "c 6,c 7,cp 7", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "D311",
            "regions": [
{        "data": [["Grupo ", "D311", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "AE2", "c 2", "RN", "c 2", "TP 4", "", "", "", "", "", "", "AE2", "Análisis Estadístico II", "2", "0", "", "", "c 2,c 2", ""], ["", "Turno 2", "MDE", "c 2", "PL", "c 2", "MDE", "cp 2", "RN", "cp Lab2", "", "", "", "MDE", "Muestreo y Diseño de Experimentos", "2", "0", "", "", "c 2,c 2,cp 2,cp Lab2", ""], ["", "Turno 3", "PGVD", "c 2", "TP", "c 4", "AE2", "cp Lab2", "PGVD", "cp 7", "", "", "", "RN", "Redes Neuronales", "2", "0", "", "", "c 2,c 4,cp Lab2,cp 7", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "PL", "Procesamiento del Lenguaje", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "PGVD", "Procesamiento de Grandes Volúmenes de Datos", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "TP", "Teoría Política", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "D411",
            "regions": [
{        "data": [["Grupo ", "D411", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "CP 2", "EIA", "2", "", "CP 2", "SN", "C4", "", "", "", "IN", "Inteligencia de Negocios", "2", "0", "", "", "CP 2,2,CP 2,C4", ""], ["", "Turno 2", "IN", "2", "SN", "C4", "IN", "2", "SN", "C4", "", "", "", "EIA", "Elementos de Inteligencia Artificial", "2", "0", "", "", "2,C4,2,C4", ""], ["", "Turno 3", "ECTS 9 (con", "C4", "CO", "2", "EIA 2", "", "", "", "", "", "", "CP", "Ciberseguridad y Privacidad", "2", "0", "", "", "C4,2", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "CO2", "Curso Optativo II", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "ECTS", "Estudios de Ciencia, Tecnología y Sociedad", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "SN/DN", "Seguridad Nacional / Defensa Nacional", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C111",
            "regions": [
{        "data": [["Grupo ", "C111", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "F", "Aula 6", "A I", "Aula 6*", "AM I", "Aula 6*", "F", "Aula 6", "", "", "", "A I", "Álgebra I", "3", "0", "", "", "Aula 6,Aula 6*,Aula 6*,Aula 6", ""], ["", "Turno 2", "L", "Aula 6*", "A I", "Aula 6*", "EF", "SEDER", "L", "Aula 6*", "A I", "Aula 6*", "", "L", "Lógica", "2", "0", "", "", "Aula 6*,Aula 6*,SEDER,Aula 6*,Aula 6*", ""], ["", "Turno 3", "P", "Aula 6", "AM I", "Aula 6*", "AM I", "Aula 6*", "P", "Aula 6", "P", "Lab", "", "P", "Programación", "3", "0", "", "", "Aula 6,Aula 6*,Aula 6*,Aula 6,Lab", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "AM I", "Análisis Matemático I", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "F", "Filosofía", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "EF", "Educación Física I", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C121",
            "regions": [
{        "data": [["Grupo ", "C121", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "P", "Aula 5", "A I", "Aula 5", "AM I", "Aula 5", "P", "Aula 5", "A I", "Aula 5", "", "A I", "Álgebra I", "3", "0", "", "", "Aula 5,Aula 5,Aula 5,Aula 5,Aula 5", ""], ["", "Turno 2", "F", "Aula 5", "AM I", "Aula 5", "EF", "SEDER", "L", "Aula 5", "P", "Lab", "", "L", "Lógica", "2", "0", "", "", "Aula 5,Aula 5,SEDER,Aula 5,Lab", ""], ["", "Turno 3", "L", "Aula 5", "A I", "Aula 5", "AM I", "Aula 5", "F", "Aula 5", "", "", "", "P", "Programación", "3", "0", "", "", "Aula 5,Aula 5,Aula 5,Aula 5", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "AM I", "Análisis Matemático I", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "F", "Filosofía", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "EF", "Educación Física I", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C122",
            "regions": [
{        "data": [["Grupo ", "C122", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "P", "Aula 5", "A I", "Aula 5", "AM I", "Aula 1", "L", "Aula 1", "P", "Lab", "", "A I", "Álgebra I", "3", "0", "", "", "Aula 5,Aula 5,Aula 1,Aula 1,Lab", ""], ["", "Turno 2", "F", "Aula 5", "AM I", "Aula 5", "EF", "SEDER", "AM I", "Aula 1", "A I", "Aula 1", "", "L", "Lógica", "2", "0", "", "", "Aula 5,Aula 5,SEDER,Aula 1,Aula 1", ""], ["", "Turno 3", "L", "Aula 5", "A I", "Aula 1", "P", "Aula 1", "F", "Aula 5", "", "", "", "P", "Programación", "3", "0", "", "", "Aula 5,Aula 1,Aula 1,Aula 5", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "AM I", "Análisis Matemático I", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "F", "Filosofía", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "EF", "Educación Física I", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C211",
            "regions": [
{        "data": [["Grupo ", "C211", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "EDA", "Estructuras de Datos y Algoritmos I", "2", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "MD", "Matemática Discreta I", "2", "0", "", "", "", ""], ["", "Turno 3", "", "", "", "", "", "", "", "", "", "", "", "AC", "Arquitectura de computadoras", "2", "0", "", "", "", ""], ["", "Turno 4", "EDA I", "c 6", "MD", "c6", "EDO", "cp 6", "MN", "cp 6", "AC", "lab", "", "EDO", "Ecuaciones Diferenciales Ordinarias", "2", "0", "", "", "c 6,c6,cp 6,cp 6,lab", ""], ["", "Turno 5", "TP", "c 6", "MN", "c 6", "EDA I", "cp 6", "TP", "c 6", "MD", "cp 6", "", "MN", "Matemática Numérica", "2", "0", "", "", "c 6,c 6,cp 6,c 6,cp 6", ""], ["", "Turno 6", "EDO", "c 6", "AC", "c 6", "EF 4:45pm a 5:35pm", "", "", "", "", "", "", "TP", "Teoría Política", "2", "0", "", "", "c 6,c 6", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C212",
            "regions": [
{        "data": [["Grupo ", "C212", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "EDA", "Estructuras de Datos y Algoritmos I", "2", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "MD", "Matemática Discreta I", "2", "0", "", "", "", ""], ["", "Turno 3", "", "", "", "", "", "", "", "", "", "", "", "AC", "Arquitectura de computadoras", "2", "0", "", "", "", ""], ["", "Turno 4", "EDA I", "c 6", "MD", "c6", "EDO I", "cp 5", "MN", "cp 5", "AC", "lab", "", "EDO", "Ecuaciones Diferenciales Ordinarias", "2", "0", "", "", "c 6,c6,cp 5,cp 5,lab", ""], ["", "Turno 5", "TP", "c 6", "MN", "c 6", "EDA I", "cp 5", "TP", "c 6", "MD", "cp 5", "", "MN", "Matemática Numérica", "2", "0", "", "", "c 6,c 6,cp 5,c 6,cp 5", ""], ["", "Turno 6", "EDO", "c 6", "AC", "c 6", "EF 4:45pm a 5:35pm", "", "", "", "", "", "", "TP", "Teoría Política", "2", "0", "", "", "c 6,c 6", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C311",
            "regions": [
{        "data": [["Grupo ", "C311", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "BD2", "Aula 9", "Est", "Aula 9", "BD2 cp", "Aula 9", "MO", "Aula 9", "", "", "", "RC", "Redes de Computadoras", "2", "0", "", "", "Aula 9,Aula 9,Aula 9,Aula 9", ""], ["", "Turno 2", "IS c", "Aula 9", "PD c", "Aula 9", "IS c", "Aula 9", "PD cp", "Aula 9", "", "", "", "IS", "Ingeniería de Software", "2", "0", "", "", "Aula 9,Aula 9,Aula 9,Aula 9", ""], ["", "Turno 3", "RC", "Aula 9", "MO", "Aula 9", "RC cp", "Aula 9", "Est cp", "Aula 9", "", "", "", "MO", "Modelos de Optimización", "2", "0", "", "", "Aula 9,Aula 9,Aula 9,Aula 9", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "BD2", "Bases de Datos II", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "PD", "Programación Declarativa", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "Est", "Estadística", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C312",
            "regions": [
{        "data": [["Grupo ", "C312", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "BD2", "Aula 9", "Est", "Aula 9", "BD2 cp", "Aula 3", "PD cp", "Aula 3", "", "", "", "RC", "Redes de Computadoras", "2", "0", "", "", "Aula 9,Aula 9,Aula 3,Aula 3", ""], ["", "Turno 2", "IS c", "Aula 9", "PD c", "Aula 9", "IS c", "Aula 3", "MO", "Aula 3", "", "", "", "IS", "Ingeniería de Software", "2", "0", "", "", "Aula 9,Aula 9,Aula 3,Aula 3", ""], ["", "Turno 3", "RC", "Aula 9", "MO", "Aula 9", "RC cp", "Aula 3", "Est cp", "Aula 3", "", "", "", "MO", "Modelos de Optimización", "2", "0", "", "", "Aula 9,Aula 9,Aula 3,Aula 3", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "BD2", "Bases de Datos II", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "PD", "Programación Declarativa", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "Est", "Estadística", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C411",
            "regions": [
{        "data": [["Grupo ", "C411", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "AM", "Aprendizaje de Máquinas", "2", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "DAA", "Diseño y Análisis de Algoritmos", "2", "0", "", "", "", ""], ["", "Turno 3", "", "", "", "", "", "", "", "", "", "", "", "SD", "Sistemas Distribuidos", "2", "0", "", "", "", ""], ["", "Turno 4", "AM", "9", "DAA", "9", "DAA", "9", "SN", "", "", "", "", "AE", "Asignatura Electiva", "2", "0", "", "", "9,9,9", ""], ["", "Turno 5", "SD 9", "", "SN", "", "AM", "9", "SN", "", "", "", "", "ECTS", "Estudios de Ciencia, Tecnología y Sociedad", "2", "0", "", "", "9", ""], ["", "Turno 6", "ECTS 9", "", "AE", "9", "SD", "9", "", "", "", "", "", "SN/DN", "Seguridad Nacional / Defensa Nacionaol", "2", "0", "", "", "9,9", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "C412",
            "regions": [
{        "data": [["Grupo ", "C412", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "AM", "Aprendizaje de Máquinas", "2", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "DAA", "Diseño y Análisis de Algoritmos", "2", "0", "", "", "", ""], ["", "Turno 3", "", "", "", "", "", "", "", "", "", "", "", "SD", "Sistemas Distribuidos", "2", "0", "", "", "", ""], ["", "Turno 4", "AM", "9", "DAA", "9", "DAA", "9", "SN", "", "", "", "", "AE", "Asignatura Electiva", "2", "0", "", "", "9,9,9", ""], ["", "Turno 5", "SD 9", "", "SN", "", "AM", "1", "SN", "", "", "", "", "ECTS", "Estudios de Ciencia, Tecnología y Sociedad", "2", "0", "", "", "1", ""], ["", "Turno 6", "ECTS 9", "", "AE", "", "SD", "9", "", "", "", "", "", "SN/DN", "Seguridad Nacional / Defensa Nacionaol", "2", "0", "", "", "9", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "M111",
            "regions": [
{        "data": [["Grupo ", "M111", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "F", "Aula 8", "IM", "Aula 8", "IAM", "Aula 8", "IA", "Aula 8", "IA", "Aula 8", "", "IAM", "Introducción al Análisis Matemático", "3", "0", "", "", "Aula 8,Aula 8,Aula 8,Aula 8,Aula 8", ""], ["", "Turno 2", "PA", "Aula 8", "IAM", "Aula 8", "EF", "SEDER", "PA Aula", "Lab", "IAM", "Aula 8", "", "IA", "Introducción al Álgebra", "3", "0", "", "", "Aula 8,Aula 8,SEDER,Lab,Aula 8", ""], ["", "Turno 3", "GA", "Aula 8", "GA", "Aula 8", "IA", "Aula 8", "GA 8", "", "", "", "", "GA", "Geometría Analítica", "2", "0", "", "", "Aula 8,Aula 8,Aula 8", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "PA", "Programación y Algoritmos", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "IM", "Introducción a la Matemática", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "F", "Filosofía", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "M211",
            "regions": [
{        "data": [["Grupo ", "M211", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "FVV", "Funciones de Varias Variables", "4", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "CAL", "Complementos de Álgebra Lineal", "3", "0", "", "", "", ""], ["", "Turno 3", "CAL", "c 3", "CAL", "c 3", "", "", "", "", "", "", "", "SP2", "Seminario de Problemas II", "2", "0", "", "", "c 3,c 3", ""], ["", "Turno 4", "FVV", "c 3", "FVV", "c 3", "FVV", "cp 3", "CAL", "cp 3", "", "", "", "AE", "Asignatura Electiva I", "2", "0", "", "", "c 3,c 3,cp 3,cp 3", ""], ["", "Turno 5", "EP", "c 7", "EP", "c 7", "FVV", "cp 3", "", "", "", "", "", "EP", "Economía Política", "2", "0", "", "", "c 7,c 7,cp 3", ""], ["", "Turno 6", "EF 4:45pm a 5:35pm", "", "SP", "2", "", "", "", "", "", "", "", "EF", "Educación Física III", "2", "0", "", "", "2", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "M311",
            "regions": [
{        "data": [["Grupo ", "M311", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "MN", "Aula 4", "EDO", "Aula 4", "MN", "4", "FV", "C 4", "FVC", "Aula 4", "", "FVC", "Funciones de variable Compleja", "2", "0", "", "", "Aula 4,Aula 4,4,C 4,Aula 4", ""], ["", "Turno 2", "FVC", "Aula 4", "OM", "Aula 4", "EDO", "Aula 4", "IE", "Aula 4", "EDO", "Aula 4", "", "IE", "Inferencia Estadística", "3", "0", "", "", "Aula 4,Aula 4,Aula 4,Aula 4,Aula 4", ""], ["", "Turno 3", "IE", "Aula 4", "TP", "Aula 4", "IE", "Aula 4", "OM", "Aula 4", "", "", "", "EDO", "Ecuaciones Diferenciales Ordinarias", "3", "0", "", "", "Aula 4,Aula 4,Aula 4,Aula 4", ""], ["", "Turno 4", "", "", "", "", "", "", "", "", "", "", "", "MN", "Matemática Numérica", "2", "0", "", "", "", ""], ["", "Turno 5", "", "", "", "", "", "", "", "", "", "", "", "OM", "Optimización Matemática I", "2", "0", "", "", "", ""], ["", "Turno 6", "", "", "", "", "", "", "", "", "", "", "", "TP", "Teoría Política", "2", "0", "", "", "", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "M411",
            "regions": [
{        "data": [["Grupo ", "M411", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "Lunes", "", "Martes", "", "Miércoles", "", "Jueves", "", "Viernes", "", "", "Abrev", "Asignaturas", "Frec", "Faltan", "Asignadas", "", "Aulas", ""], ["", "Turno 1", "", "", "", "", "", "", "", "", "", "", "", "MI", "Medida e Integración", "2", "0", "", "", "", ""], ["", "Turno 2", "", "", "", "", "", "", "", "", "", "", "", "GD", "Geometría Diferencial", "2", "0", "", "", "", ""], ["", "Turno 3", "", "", "", "", "", "", "", "", "", "", "", "HM", "Historia de la Matemática", "2", "0", "", "", "", ""], ["", "Turno 4", "GD", "4", "HM", "4", "MI", "4", "AO", "2", "", "", "", "ECTS", "Estudios de Ciencia, Tecnología y Sociedad", "2", "0", "", "", "4,4,4,2", ""], ["", "Turno 5", "MI", "4", "HM", "4", "GD", "4", "AO", "3", "", "", "", "AO2", "Asignatura Optativa II", "2", "0", "", "", "4,4,4,3", ""], ["", "Turno 6", "ECTS 9 (Con", "C4", "GD", "4", "", "", "", "", "", "", "", "AO3", "Asignatura Optativa III", "2", "0", "", "", "C4,4", ""]],
        "formulas": [{"row": 4, "col": 18, "value": "=COUNTIF($C$4:$L$9,N4)"}, {"row": 5, "col": 18, "value": "=COUNTIF($C$4:$L$9,N5)"}, {"row": 6, "col": 18, "value": "=COUNTIF($C$4:$L$9,N6)"}, {"row": 7, "col": 18, "value": "=COUNTIF($C$4:$L$9,N7)"}, {"row": 8, "col": 18, "value": "=COUNTIF($C$4:$L$9,N8)"}, {"row": 9, "col": 18, "value": "=COUNTIF($C$4:$L$9,N9)"}, {"row": 4, "col": 17, "value": "=(P4-R4)"}, {"row": 5, "col": 17, "value": "=(P5-R5)"}, {"row": 6, "col": 17, "value": "=(P6-R6)"}, {"row": 7, "col": 17, "value": "=(P7-R7)"}, {"row": 8, "col": 17, "value": "=(P8-R8)"}, {"row": 9, "col": 17, "value": "=(P9-R9)"}, {"row": 10, "col": 14, "value": "=COUNTA(N$4:N$9)"}, {"row": 10, "col": 13, "value": "=\"Total:\""}, {"row": 11, "col": 13, "value": "=SUM(P$4:P$9)"}, {"row": 11, "col": 12, "value": "=\"Σ Frec:\""}],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10, 14: 10, 15: 10, 16: 10, 17: 10, 18: 10, 19: 10, 20: 10, 21: 10},
        "border_color": "B7B7B7"}            ]
        },
        {
            "title": "Aulas",
            "regions": [
{        "data": [["", "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Lab", ""], ["", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "Lunes", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Lab", ""], ["", "1", "", "", "", "", "", "C111,C112", "", "", "", "C113", ""], ["", "2", "", "", "", "", "C112", "C113", "", "", "", "", ""], ["", "3", "", "", "", "", "", "C111,C113", "", "C112", "", "", ""], ["", "4", "", "", "", "", "", "", "", "", "", "", ""], ["", "5", "", "", "", "", "", "", "", "", "", "", ""], ["", "6", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "Martes", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Lab", ""], ["", "1", "", "C112", "", "", "", "C111", "C113", "", "", "", ""], ["", "2", "C111", "", "", "", "", "C112,C113", "", "", "", "", ""], ["", "3", "", "", "", "", "", "C111,C112,C113", "", "", "", "", ""], ["", "4", "", "", "", "", "", "", "", "", "", "", ""], ["", "5", "", "", "", "", "", "", "", "", "", "", ""], ["", "6", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "Miércoles", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Lab", ""], ["", "1", "", "", "", "", "C112", "C111", "", "C113", "", "", ""], ["", "2", "", "", "", "", "", "", "", "", "", "", ""], ["", "3", "", "C112", "", "", "C113", "C111", "", "", "", "", ""], ["", "4", "", "", "", "", "", "", "", "", "", "", ""], ["", "5", "", "", "", "", "", "", "", "", "", "", ""], ["", "6", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "Jueves", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Lab", ""], ["", "1", "C113", "", "", "", "C112", "C111", "", "", "", "", ""], ["", "2", "C113", "", "", "", "C112", "C111", "", "", "", "", ""], ["", "3", "C113", "", "", "", "C112", "C111", "", "", "", "", ""], ["", "4", "", "", "", "", "", "", "", "", "", "", ""], ["", "5", "", "", "", "", "", "", "", "", "", "", ""], ["", "6", "", "", "", "", "", "", "", "", "", "", ""], ["", "", "", "", "", "", "", "", "", "", "", "", ""], ["", "Viernes", "1", "2", "3", "4", "5", "6", "7", "8", "9", "Lab", ""], ["", "1", "", "", "", "", "", "", "", "", "", "", ""], ["", "2", "", "", "", "", "", "", "", "", "", "C112", ""], ["", "3", "", "", "", "", "C111", "", "", "", "", "", ""], ["", "4", "", "", "", "", "", "", "", "", "", "", ""], ["", "5", "", "", "", "", "", "", "", "", "", "", ""], ["", "6", "", "", "", "", "", "", "", "", "", "", ""]],
        "column_widths": {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10, 10: 10, 11: 10, 12: 10, 13: 10},
        "border_color": "B7B7B7"}            ]
        }    ]
}

generar_excel_personalizado(config, "Horario_Facultad.xlsx")

if __name__=='__main__':
    print('OK: Horario_Facultad.xlsx')
