;; variables_horario_tv.lisp — Datos del horario TV
;; Cada día tiene *-hour* (string) y *-progs* (lista de triples (nombre duracion tipo))

(defparameter *lunes-hour* "16:00")
(defparameter *lunes-progs*
  '(("EL TIEMPO Y LA MEMORIA"          5  "informativo")
    ("COORDENADAS"                     5  "informativo")
    ("REVISTA HOLA HABANA"            50  "revista")
    ("DÉCADAS MILAGROSAS"            30  "musical")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("POWER RANGERS"                  30  "infantil")
    ("CINECITO EN TV"                 25  "cine")
    ("COORDENADAS INFANTILES"          5  "informativo")
    ("VE Y MIRA"                      30  "cine")
    ("MÚSICA HABANA"                  30  "musical")
    ("HABANA COLECCIÓN"               30  "cultural")
    ("MÚSICA SÍ"                      60  "musical")
    ("D DISEÑO"                       15  "cultural")
    ("SIN PUNTOS SUSPENSIVOS"         15  "entrevista")
    ("NOVELA “LA NIETA ELEGIDA”"      45  "ficción")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("SERIE “CRÍMENES MAYORES”"       45  "ficción")))

(defparameter *martes-hour* "19:30")
(defparameter *martes-progs*
  '(("TODO POP"                        30  "musical")
    ("BREVES ESTACIONES"              30  "cultural")
    ("SALUDARTE"                      15  "salud")
    ("SECUENCIA"                      15  "cultural")
    ("RITMO CLIP"                     30  "musical")
    ("TRIANGULO DE LA CONFIANZA"      30  "entrevista")
    ("NOVELA “LA NIETA ELEGIDA”"      45  "ficción")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("SERIE “CRÍMENES MAYORES”"       45  "ficción")))

(defparameter *miercoles-hour* "19:45")
(defparameter *miercoles-progs*
  '(("COSAS DEL CINE"                 15  "cine")
    ("RITMO CLIP"                     30  "musical")
    ("BANDA SONORA JUVENIL"           30  "cultural")
    ("VE Y MIRA"                      30  "cine")
    ("MÚSICA DEL MUNDO"               30  "musical")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("CINEMA HABANA"                  77  "cine")))

(defparameter *jueves-hour* "16:00")
(defparameter *jueves-progs*
  '(("EL TIEMPO Y LA MEMORIA"          5  "informativo")
    ("COORDENADAS"                     5  "informativo")
    ("REVISTA HOLA HABANA"            50  "revista")
    ("SALUDARTE"                      15  "salud")
    ("SECUENCIA"                      15  "cultural")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("CAZADOR DE TROLES"              30  "infantil")
    ("EL MUNDO DE CRAIG"              15  "animacion")
    ("ÁNIMA"                          45  "animacion")
    ("PAPEL EN BLANCO"                30  "cultural")
    ("MÚSICA DEL MUNDO"               30  "musical")
    ("TRAVESÍA"                       15  "cultural")
    ("DONDE VA LA HABANA"             15  "cultural")
    ("BANDA SONORA"                   30  "musical")
    ("ESTA ES MI PEÑA"                30  "musical")
    ("NOVELA “LA NIETA ELEGIDA”"      45  "ficción")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("SERIE “CRÍMENES MAYORES”"       45  "ficción")))

(defparameter *viernes-hour* "16:30")
(defparameter *viernes-progs*
  '(("GEN HABANERO"                   60  "documental")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("TIENE QUE VER"                 115  "cine")
    ("COORDENADAS INFANTILES"          5  "informativo")
    ("ALGO ENTRE MANOS"               30  "cultural")
    ("BREVES ESTACIONES"              30  "cultural")
    ("DÉCADAS MILAGROSAS"            30  "musical")
    ("SIN PUNTOS SUSPENSIVOS"         15  "entrevista")
    ("YO BAILO"                       15  "musical")
    ("NOVELA “LA NIETA ELEGIDA”"      45  "ficción")
    ("HABANA NOTICIARIO"              30  "informativo")
    ("SERIE “CRÍMENES MAYORES”"       45  "ficción")))

(defparameter *sabado-hour* "16:00")
(defparameter *sabado-progs*
  '(("EL TIEMPO Y LA MEMORIA"          5  "informativo")
    ("COORDENADAS"                     5  "informativo")
    ("CUENTAS VERDE LIMÓN"            35  "infantil")
    ("BANDA SONORA JUVENIL"           30  "cine")
    ("TRAVESÍA"                       15  "cultural")
    ("TODO POP"                       30  "musical")
    ("SERIE JUVENIL “SABRINA…”"       45  "ficción")
    ("LIBRE ACCESO"                   45  "informativo")
    ("JUGADA PERFECTA"                30  "deporte")
    ("QUE LA MÚSICA NO FALTE"         15  "musical")
    ("COSAS DEL CINE"                 15  "cine")
    ("MÚSICA HABANA"                  30  "musical")
    ("X DISTANTE"                     90  "animacion")
    ("MÚSICA SI"                      90  "musical")))

(defparameter *domingo-hour* "02:00")
(defparameter *domingo-progs*
  '(("EL TIEMPO Y LA MEMORIA"          5  "informativo")
    ("COORDENADAS"                     5  "informativo")
    ("CANAL HABANA DEPORTES"         890  "deporte")
    ("LATINOS"                        60  "musical")
    ("PAPEL EN BLANCO"                30  "cultural")
    ("ALGO ENTRE MANOS"               30  "cultural")
    ("VERDE HABANA"                   15  "documental")
    ("GEN HABANERO"                   15  "documental")
    ("TRIANGULO DE LA CONFIANZA"      30  "entrevista")
    ("BANDA SONORA"                   30  "musical")
    ("CINE +"                        205  "cine")))

;; Para la hoja de resumen — pares (nombre hora progs)
(defparameter *semana-resumen*
  (list (list "Lunes"     *lunes-hour*    *lunes-progs*)
        (list "Martes"    *martes-hour*   *martes-progs*)
        (list "Miércoles" *miercoles-hour* *miercoles-progs*)
        (list "Jueves"    *jueves-hour*   *jueves-progs*)
        (list "Viernes"   *viernes-hour*  *viernes-progs*)
        (list "Sábado"    *sabado-hour*   *sabado-progs*)
        (list "Domingo"   *domingo-hour*  *domingo-progs*)))
